-- Data dump for table: agricultural_input_insecticides
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C001', 'Brown planthopper', 'Chemical', 'Thiamethoxam', '25% WG', '100', 'g/ha', '500 L/ha', 'Foliar spray', 'ETL / infestation');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C002', 'Aphid', 'Chemical', 'Imidacloprid', '17.8% SL', '300', 'ml/ha', '500–600 L/ha', 'Foliar spray', 'Pest appearance');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C003', 'Fall armyworm', 'Chemical', 'Spinetoram', '11.7% SC', '35', 'g a.i./ha', 'As recommended', 'Foliar spray', 'Stage-specific');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C004', 'Pod borer', 'Chemical', 'Chlorantraniliprole', '18.5% SC', '150', 'ml/ha', '500–750 L/ha', 'Foliar spray', 'Flowering/podding');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C005', 'Aphid', 'Chemical', 'Imidacloprid', '17.8% SL', '300', 'ml/ha', '500–600 L/ha', 'Foliar spray', 'Pest appearance');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C006', 'Whitefly', 'Chemical', 'Imidacloprid', '17.8% SL', '0.5', 'ml/L', '—', 'Foliar spray', 'Vector build-up');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C007', 'Whitefly', 'Chemical', 'Imidacloprid', '17.8% SL', '0.5', 'ml/L', '—', 'Foliar spray', 'Vector build-up');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C008', 'Mustard aphid', 'Chemical', 'Thiamethoxam', '25% WG', '20–40', 'g/acre', '200–400 L/acre', 'Foliar spray', 'Aphid appearance');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C009', 'Aphid', 'Chemical', 'Thiamethoxam', '25% WG', '40', 'g/acre', '200 L/acre', 'Foliar spray', 'Aphid infestation');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C010', 'Fruit borer', 'Chemical', 'Indoxacarb', '14.5% SC', '400–500', 'ml/ha', '300–600 L/ha', 'Foliar spray', 'ETL / infestation');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C011', 'Thrips', 'Chemical', 'Dimethoate', '30% EC', '660', 'ml/ha', '500–1000 L/ha', 'Foliar spray', 'Pest appearance');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C012', 'Shoot & fruit borer', 'Chemical', 'Chlorantraniliprole', '18.5% SC', '200', 'ml/ha', '500–750 L/ha', 'Foliar spray', 'ETL / infestation');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C013', 'Diamondback moth', 'Chemical', 'Spinosad', '2.5% SC', '600–700', 'ml/ha', '500 L/ha', 'Foliar spray', 'Pest appearance');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C014', 'Diamondback moth', 'Chemical', 'Spinosad', '2.5% SC', '600–700', 'ml/ha', '500 L/ha', 'Foliar spray', 'Pest appearance');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C015', 'Early shoot borer', 'Chemical', 'Chlorantraniliprole', '18.5% SC', '375', 'ml/ha', '1000 L/ha', 'Soil/sett treatment', 'Planting / early crop');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C016', 'Jute semilooper', 'Chemical', 'Emamectin benzoate', '5% SG', '3', 'g/ha', '10 L/ha', 'Foliar spray', 'Pest appearance');
INSERT INTO "agricultural_input_insecticides" ("crop_id", "insect_pest", "insecticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "water_volume", "application_method", "application_timing") VALUES ('C017', 'Thrips', 'Chemical', 'Spinosad', '45% SC', '160', 'g/ha', '500 L/ha', 'Foliar spray', 'Pest infestation');
