-- Data dump for table: agricultural_input_presticides
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C001', 'Blast', 'Fungicide', 'Azoxystrobin 18.2% + Difenoconazole 11.4%', 'SC', '0.1', '%', 'Foliar spray', 'Disease initiation');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C002', 'Leaf/Stripe Rust', 'Fungicide', 'Propiconazole', '25% EC', '500', 'ml/ha', 'Foliar spray', 'Disease appearance');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C003', 'Leaf Blight', 'Fungicide', 'Carbendazim 12% + Mancozeb 63%', 'WP', '1000', 'g/ha', 'Foliar spray', 'Disease initiation');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C004', 'Fusarium Wilt / Root Rot', 'Fungicide / Seed treatment', 'Tebuconazole', '54% FS', '2', 'g/kg seed', 'Seed treatment', 'Before sowing');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C005', 'Wilt / Rust', 'Fungicide', 'Mancozeb', '75% WP', '2', 'g/L water', 'Foliar spray', 'Disease appearance');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C006', 'Yellow Mosaic', 'Biological / Vector management', 'No direct fungicide', '—', '—', '—', '—', '—');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C007', 'Yellow Mosaic', 'Biological / Vector management', 'No direct fungicide', '—', '—', '—', '—', '—');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C008', 'Alternaria Blight', 'Fungicide', 'Metalaxyl 8% + Mancozeb 64%', 'WP', '1000', 'g/acre', 'Foliar spray', 'Disease initiation');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C009', 'Late Blight', 'Fungicide', 'Metalaxyl-M 4% + Mancozeb 64%', 'WP', '1700', 'g/ha', 'Foliar spray', 'Preventive / initial infection');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C010', 'Early/Late Blight', 'Fungicide', 'Azoxystrobin 18.2% + Difenoconazole 11.4%', 'SC', '0.1', '%', 'Foliar spray', 'Preventive / disease initiation');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C011', 'Purple Blotch', 'Fungicide', 'Difenoconazole', '25% EC', '40', 'ml/acre', 'Foliar spray', 'Initial infection');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C012', 'Shoot & Fruit Borer', 'See Insecticide table', '—', '—', '—', '—', '—', '—');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C013', 'Downy Mildew', 'Fungicide', 'Metalaxyl + Mancozeb', 'WP', '25', 'g/L water', 'Foliar spray', 'Disease appearance');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C014', 'Downy Mildew', 'Fungicide', 'Metalaxyl + Mancozeb', 'WP', '25', 'g/L water', 'Foliar spray', 'Disease appearance');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C015', 'Red Rot / Smut', 'Fungicide', 'Azoxystrobin 18.2% + Difenoconazole 11.4%', 'SC', '0.1', '%', 'Foliar spray', 'Disease initiation');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C016', 'Stem Rot / Wilt', 'Biological', 'Trichoderma spp.', 'SC', '5', 'kg/ha', 'Soil application', 'Before sowing');
INSERT INTO "agricultural_input_presticides" ("crop_id", "disease", "pesticide_type", "active_ingredient", "formulation", "recommended_dose", "dose_unit", "application_method", "application_timing") VALUES ('C017', 'Anthracnose / Fruit Rot', 'Fungicide', 'Carbendazim 12% + Mancozeb 63%', 'WP', '1', 'g/L water', 'Foliar spray', 'Disease initiation');
