-- Data dump for table: agricultural_input_fertilizers
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C001', 'NPK', 'N-P-K', '100:60:40', 'kg/ha', 'Basal + splits', 'Soil', 'General; adjust to soil test');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C002', 'Urea + SSP + MOP', 'N-P-K', '3 days 08:34:09', 'kg/acre*', 'Basal + top dressing', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C003', 'NPK + ZnSO₄', 'N-P-K + Zn', '150:65:65 + 25', 'kg/ha', 'Basal + top dressing', 'Soil', 'Irrigated');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C004', 'NPK', 'N-P-K', '20:40:20', 'kg/ha', 'At sowing', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C005', 'NPK', 'N-P-K', '20:40:20', 'kg/ha', 'At sowing', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C006', 'NPK + FYM', 'N-P-K', '20:40:0 + 5', 'kg/ha + t/ha', 'Basal', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C007', 'NPK + FYM', 'N-P-K', '20:40:0 + 5', 'kg/ha + t/ha', 'Basal', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C008', 'Urea + SSP + MOP', 'N-P-K', '70:~30:~12', 'kg/acre*', 'Basal + top dressing', 'Soil', 'General; adjust to soil test');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C009', 'NPK', 'N-P-K', '3 days 03:50:50', 'kg/ha', 'Basal + splits', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C010', 'NPK + FYM', 'N-P-K', '120:80:80 + 15', 'kg/ha + t/ha', 'Basal + splits', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C011', 'NPKS + FYM', 'N-P-K-S', '110:40:60:20 + 15', 'kg/ha + t/ha', 'Basal + splits', 'Soil/fertigation', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C012', 'NPK + FYM', 'N-P-K', '150:120:120 + 15', 'kg/ha + t/ha', 'Basal + splits', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C013', 'NPK', 'N-P-K', '120:60:60', 'kg/ha', 'Basal + top dressing', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C014', 'NPK', 'N-P-K', '120:60:60', 'kg/ha', 'Basal + top dressing', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C015', 'NPK + S', 'N-P-K-S', '150:60:60 + 40', 'kg/ha', 'Basal + splits', 'Soil', 'General; S if deficient');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C016', 'NPK', 'N-P-K', '1 day 16:20:20', 'kg/ha', 'Basal + top dressing', 'Soil', 'General');
INSERT INTO "agricultural_input_fertilizers" ("crop_id", "fertilizer_type", "nutrient", "recommended_dose", "dose_unit", "application_timing", "application_method", "condition") VALUES ('C017', 'NPK + FYM', 'N-P-K', '100:50:50 + 15', 'kg/ha + t/ha', 'Basal + splits', 'Soil', 'General');
