-- Data dump for table: crop_knowledge_(1)_crop_requirements
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C001', 'Fertile, well-drained', 'Loamy ', '5.5', '7.5', '15°C', '33°C', 'Needs abundant water', 'Prefers fields with good bunding', 'low', 'high', '70', '90', '60', '80', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C002', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '10°C', '30°C', 'Moderate', 'Good drainage is important', 'Moderate', 'Low', '50', '70', '50', '70', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C003', 'Well-drained, fertile soils', 'Sandy loam ', '5.5', '7.5', '15°C', '32°C', 'Moderate', 'Good drainage required', 'Moderate', 'Low', '50', '70', '50', '70', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C004', 'Well-drained', 'Sandy loam ', '6.0', '7.5', '10°C', '30°C', 'Moderate', 'Good drainage required', 'Moderate', 'Low', '50', '70', '40', '60', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C005', 'Well-drained', 'Loamy ', '6.0', '7.5', '10°C', '30°C', 'Low', 'Good drainage required', 'Moderate', 'Low', '35', '55', '40', '60', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C006', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '15°C', '35°C', 'Low', 'Good drainage required', 'Moderate', 'Low', '35', '55', '40', '60', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C007', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '15°C', '35°C', 'Low', 'Good drainage required', 'Moderate', 'Low', '35', '55', '40', '60', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C008', 'Well-drained, fertile soils', 'Sandy loam ', '7.0', '8.5', '10°C', '30°C', 'Low', 'Good drainage required', 'Moderate', 'Low', '35', '55', '40', '60', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C009', 'Well-drained, fertile soils', 'Sandy loam ', '5.5', '7.0', '15°C', '25°C', 'Moderate', 'Good drainage essential', 'Low', 'Low', '50', '70', '50', '80', '18000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C010', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '15°C', '30°C', 'Moderate', 'Good drainage essential', 'Low', 'Low', '50', '70', '50', '70', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C011', 'Well-drained, fertile soils', 'Fertile loamy ', '6.0', '7.5', '13°C', '25°C', 'Moderate', 'Good drainage required', 'Low', 'Low', '50', '70', '55', '70', '18000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C012', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '15°C', '32°C', 'Moderate', 'Good drainage required', 'Moderate', 'Low', '50', '70', '50', '70', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C013', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '13°C', '25°C', 'Moderate', 'Good drainage essential', 'Low', 'Low', '50', '70', '60', '80', '18000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C014', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '13°C', '25°C', 'Moderate', 'Good drainage essential', 'Low', 'Low', '50', '70', '60', '80', '18000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C015', 'Well-drained, fertile soils', 'Deep loam', '6.5', '8.0', '20°C', '35°C', 'High', 'Good drainage  preferred', 'Moderate', 'Low', '65', '85', '60', '80', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C016', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '20°C', '35°C', 'High', 'Good drainage required', 'low', 'Low', '65', '85', '70', '90', '32000', '100000');
INSERT INTO "crop_knowledge_(1)_crop_requirements" ("crop_id", "soil_type", "soil_texture", "min_ph", "max_ph", "min_opt_temp", "max_opt_temp", "water", "drainage", "drought_tolerance", "waterlogging_tolerance", "min_soil_moisture_%", "max_soil_moisture_%", "min_humidity_%", "max_humidity_%", "min_light_lux", "max_light_lux") VALUES ('C017', 'Well-drained, fertile soils', 'Sandy loam ', '6.0', '7.5', '15°C', '32°C', 'Moderate', 'Good drainage required', 'Moderate', 'Low', '50', '70', '50', '70', '32000', '100000');
