-- Data dump for table: crop_knowledge_(1)_crop_season
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C001', 'May', 'June ', 'October', 'November', '120–145 days ');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C002', 'November', 'December', 'March', 'April', '120–140 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C003', 'June', 'July', 'September', 'October', '90–120 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C004', 'September ', 'November ', 'February', 'March', '110–130 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C005', 'November', 'November', 'February', 'March', '100–120 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C006', 'September', 'October', 'January', 'February', '60–70 days ');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C007', 'September', 'October', 'January', 'February', '60–70 days ');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C008', 'October', 'November', 'February', 'March', '110–120 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C009', 'September', 'October', 'January', 'February', '90–100 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C010', 'October', 'November', 'January', 'March', '90–110 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C011', 'September ', 'October ', 'March', 'April', '120–150 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C012', 'October', 'November', 'January', 'April', '120–130 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C013', 'August', 'September', 'December', 'February', '100–120 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C014', 'June/August/October', 'July/September/November ', 'October ', 'March', '90–120 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C015', 'June', 'July', 'July (next year)', 'October (next year)', '12–15 months');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C016', 'March', 'April', 'July', 'September', '120–150 days');
INSERT INTO "crop_knowledge_(1)_crop_season" ("crop_id", "sowing_start_month", "sowing_end_month", "harvest_start_month", "harvest_end_month", "crop_duration_days") VALUES ('C017', 'September', 'October', 'January', 'April', '120–150 days');
